services:
 mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - cj-mongo:/home/etc/data
    networks:
      - cj-network
 server:
    build: server/.
    restart: always
    ports:
      - "8000:5000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - PORT=5000
    env_file: server/.env
    networks:
      - cj-network
 app:
    build: app/.
    ports:
      - "80:80"
    env_file: app/.env
    networks:
      - cj-network
volumes:
  cj-mongo:
networks:
  cj-network:
    driver: bridge
  
